<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository {

    public function getAdvertWithCategories(array $categoryNames) {
        
        $qb = $this
                ->createQueryBuilder('a')
                ->innerJoin(a.categories, 'cat')
                ->addSelect('cat');
        
        $qb->where($qb->expr()->in('cat.name', $categoryNames));
        
        return $qb->getQuery()->getResult();  
    }
    
    public function getApplicationsWithAdvert($limit){
        
        $qb = $this
                ->createQueryBuilder('a')
                ->innerJoin('a.applications', 'app')
                ->addSelect('app')
                ->orderBy('app.date','DESC')
                ->setMaxResults($limit);
        
        return $qb->getQuery()->getResult();
    }

}
